export const Img = {
  splashscreen: require('../assets/splashlogo.png'),
  mainlogo: require('../assets/mainlogo.png'),
  eyeopen: require('../assets/eyeopen.png'),
  eyeclosed: require('../assets/eyeclosed.png'),
  home: require('../assets/home.png'),
  chat: require('../assets/chat.png'),
  person: require('../assets/person.png'),
  homebg: require('../assets/homebg.png'),
  bell: require('../assets/bell.png'),
  camera: require('../assets/camera.png'),
  cross: require('../assets/cross.png'),
  character: require('../assets/character.png'),
  edit: require('../assets/edit.png'),
  bin: require('../assets/bin.png'),
  cloud: require('../assets/cloud.png'),
  location: require('../assets/location.png'),
  uploaded: require('../assets/uploaded.png'),
  save: require('../assets/save.png'),
  comment: require('../assets/comment.png'),
  like: require('../assets/like.png'),
  share: require('../assets/share.png'),
  smile: require('../assets/smile.png'),
  gallery: require('../assets/gallery.png'),
  camerablack: require('../assets/camerablack.png'),
  pfuseradd: require('../assets/pfuseradd.png'),
  pfchat: require('../assets/pfchat.png'),
  pfstar: require('../assets/pfstar.png'),
  pflogout: require('../assets/pflogout.png'),
  pfpeople: require('../assets/pfpeople.png'),
  pfuser2: require('../assets/pfuser2.png'),
  pfuser: require('../assets/pfuser.png'),
  pfarrow: require('../assets/pfarrow.png'),
  pfsearch: require('../assets/pfsearch.png'),
  TTBwatch: require('../assets/TTBwatch.png'),
  TTBphotos: require('../assets/TTBphotos.png'),
  TTBplay: require('../assets/TTBplay.png'),
  TTBabout: require('../assets/TTBabout.png'),
  TTBfriends: require('../assets/TTBfriends.png'),
  education: require('../assets/education.png'),
  event: require('../assets/event.png'),
  family: require('../assets/family.png'),
  map: require('../assets/map.png'),
  menu: require('../assets/menu.png'),
  searchmenu: require('../assets/searchmenu.png'),
  telephone: require('../assets/telephone.png'),
  couple: require('../assets/couple.png'),
  email: require('../assets/email.png'),
  house: require('../assets/house.png'),
  link: require('../assets/link.png'),
  case: require('../assets/case.png'),
  prayer: require('../assets/prayer.png'),
  backarrow: require('../assets/backarrow.png'),
  plusfill: require('../assets/plusfill.png'),
  building: require('../assets/building.png'),
  radiofill: require('../assets/radiofill.png'),
  radioempty: require('../assets/radioempty.png'),
  calendar: require('../assets/calendar.png'),
  cameraplus: require('../assets/cameraplus.png'),
  playbutton: require('../assets/playbutton.png'),
  security: require('../assets/security.png'),
  info: require('../assets/info.png'),
  backarr: require('../assets/backarr.png'),
  menudots: require('../assets/menudots.png'),
  sendchat: require('../assets/sendchat.png'),
  url: require('../assets/url.png'),
  gender: require('../assets/gender.png'),
  language: require('../assets/language.png'),











  
};
