export const Strings = {
  email:'Email',
  cancel:'Cancel',
  save:'Save',
  delete:'Delete',
  emailorphone:'Email or phone',
  password: 'Password',
  conpassword: 'Confirm Password',
  resetpass:'Reset Password',
  login:'Login',
  forgetpass:'Forget Password ?',
  noaccount:`Don't Have An Account ?`,
  createacc:'Create an account',
  quicksafe:`It's real quick and safe`,
  username:'User name',
  fullname:'Full name',
  mobileoremail:'Mobile number or email',
  quicksafe:`It's real quick and safe`,
  alreadyacc:'Already Have An Account ?',
  bysigningup:`By signing up, you agree to our Terms, Data Policy and Cookies Policy.`,
  signup:'SIGN UP',
  enteremail: 'Enter Registered Email',
  submit:'Submit',
  bklogin:'Back to Login',
  enterotp:'Enter OTP',
  verify:'Verify',
  whatgoingon:'What is going on in your gaming world today',
  nopost:`You don't have any posts yet.`,
  novideos:`You don't have any videos yet.`,
  nofriends:`No friends to show`,
  imgorvideo:'Upload Images or Videos',
  saysomething:'Say Something',
  overview:'Overview',
  addhometw:'Add your home town',
  addwork:'Add Work Place',
  adduni:'Add university',
  addschl:'Add High School',
  addmobile:'Add Mobile Phone',
  addemail:'Add Your Email Address',
  addwebsite:'Add a website',
  addreligios:'Add your religious view',
  addgender:'Add your gender',
  addbirth:'Add your birth of date',
  addrelation:'Add relationship status',
  addfamily:'Add family members',
  addfamilyname:'write member name',
  addnamepron:'Add a name pronunciation',
  addnickname:'Add a nickname',
  addyournickname:'Add your nickname',
  addquote:'Add a quote',
  enterdate:'Enter Date',
  selectgender:'Select Gender',
  addlang:'Add language',
  hometw:'Home Town',
  currentcity:'Current City',
  placedlive:'Place Lived',
  WandE:'Work & Education',
  FandR:'Family & Relationship',
  work:'Work',
  univ:'University',
  highsch:'High School',
  contactNinfo:'Contact & Basic Info',
  contactinfo:'Contact Info',
  websitelinks:'Websites and Social Links',
  basicinfo:'Basic Info',
  relationship:'Relationship',
  familymen:'Family Members',
  detailsabout:'Details About You',
  aboutyou:'About You',
  namespron:'Names Pronunciation',
  othername:'Other Names',
  favquotes:'Favourite Quotes',
  writedetails:'Write some details about you',
  writeyourdet:'Write Your Details',
  lifeevents:'Life Events',
  addevent:'Add life events',
  yourphoto:'Your Photos',
  albums:'Albums',
  yourvideo:'Your Videos',
  searchfriends:`Search your friend's...`,
  friendsreq:'Friend Request',
  findfriends:'Find Friends',
  allfriends:'All Friends',
  following:'Following',
  follow:'Follow',
  peopleyouknow:'People you may know',
  addfriend:'Add Friend',
  pleaseaddsome:'please add some friends list',
  nofriendssuggest:'Oops no friends suggestions',
  generalsettings:'General Account Settings',
  securitylogin:'Security and Login',
  yourinfo:'Your social information',
  putadds:'Put your ads here!',
  chat:'Chat',
  oopsnofriends:'Opps you have not made any friends till now',
  addfriends:'no friends please add some friends to chat with them 😀',










  //old
  loginAsUser: 'Login as User',
  loginAsBusiness: 'Login as Business',
  addProfile: 'Add a profile picture',
  next: 'Next',
  skip: 'Skip',
  businessAddress: 'Business Address',
  searchLocation: 'Search Location',
  selectLocation: 'Select Location',
  addressDetails: 'Address Details',
  locationName: 'Location name',
  flatNo: 'Flat/Villa No.',
  flatVilla: 'Flat/Villa here',
  building: 'Building/Villa',
  buildingName: 'Building name here',
  street: 'Street',
  streetName: 'Street name here',
  area: 'Area',
  areaName: 'Area name here',
  directions: 'Directions',
  businessTimings: 'Business Timings',
  saveLocationTime: 'Save Location and Timings',
  to: 'To',
  services: 'Services',
  servicesOffer: 'What services do you offer?',
  hair: 'Hair',
  makeup: 'Makeup',
  skincare: 'Skincare',
  nails: 'Nails',
  hairRemoval: 'Hair Removal',
  tanning: 'Tanning',
  finish: 'Finish',
  new: 'New',
  upcoming: 'Upcoming',
  newBookings: 'New Bookings',
  accept: 'Accept',
  reject: 'Reject',
  no: 'No',
  reschedule: 'Reschedule',
  home: 'Home',
  staff: 'Staff',
  orders: 'Orders',
  profile: 'Profile',
  new: 'New',
  upcoming: 'Upcoming',
  newBookings: 'New Bookings',
  rejectBookingRequest: 'Are you sure you want to reject this booking request?',
  upcomingBookings: 'Upcoming Bookings',
  orderDetail: 'Order Detail',
  customerInfo: 'Customer Information',
  detail: 'Detail',
  service: 'Service',
  price: 'Price',
  duration: 'Duration',
  appointmentDate: 'Appointment Date',
  appointmentTime: 'Appointment Time',
  professional: 'Professional',
  serviceLocation: 'Service Location',
  noteCustomer: 'Note from customer:',
  note: 'Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae eleifend ac.',
  detailedLocation: 'Detailed location goes here',
  addpaymentMethod: 'Add Payment Method',
  debitCreditCard: 'Debit/Credit Card',
  giftCard: 'Gift Card',
  credit: 'Credit',
  payPal: 'PayPal',
  applePay: 'Apple Pay',
  addDebitCreditCard: 'Add Debit/Credit Card',
  nameOnCard: 'Name on card',
  cardNumber: 'Card Number',
  cardExpiry: 'Card Expiry',
  CVV: 'CVV',
  saveCard: 'Save card',
  addLater: 'Add Later',
  costBreakdown: 'Cost Breakdown',
  total: 'Total',
  straightHair: 'Straight Hair',
  visitingCharges: 'Visiting Charges',
  address: 'Address',
  locationgoeshere: 'Some address line goes here',
  amend: 'Amend',
  bookService: 'Book Service',
  addons: 'Add ons',
  selectDate: 'Select Date',
  selectTime: 'Select Time',
  selectProfessional: 'Select Professional',
  optional: ' (Optional)',
  optionalSelection:
    'Selecting professional is optional, we’ll select a professional for you if you choose not to select by yourself.',
  addService: ' Add Service',
  selectService: 'Select Service',

  //Staff
  professionals: 'Professionals',
  professionalListed: '5 Staff Professionals Listed',
  hairProfessionals: 'Hair Professionals',
  addA: 'Add a ',
  addProfessional: 'Add a Professional',
  addProf: 'Add Professional',
  add: 'Add',
  firstName: 'First Name',
  lastName: 'Last Name',
  selectServices: 'Select Services',
  addRemoveServices: 'Add/Remove Services',
  addProTo: 'Add a Professional to ',
  addNewProfessional: 'Add a new professional',
  addFromexisting: 'Add from existing',
  remove: 'Remove',
  removeFromList: 'Remove from this list',
  //Services
  addAService: 'Add a Service',
  addService: 'Add Service',
  servicesListed: '5 services listed',
  addOns: 'Add Ons',
  saveService: 'Save Service',
  serviceName: 'Service Name',
  serviceCharges: 'Service Charges',
  timeDuration: 'Time Duration',
  serviceAvailableAt: 'Will this service be available at customer’s location?',
  yes: 'Yes',
  addOnsOptional: 'Add ons (Optional)',
  addOnName: 'Add On Name',
  addMore: 'Add More',
  edit: 'Edit',
  editdetails: 'Edit Details',
  removeAddon: 'Are you sure you want to remove',
  discard: 'Discard',
  saveChanges: 'Save Changes',
  //profile
  businessProfile: 'Business Profile',
  paymentOptions: 'Payment Options',
  settings: 'Settings',
  help: 'Help',
  manageAddress: 'Manage addresses and other info',
  managePaymentOptions: 'Manage payment options',
  notificationsandSecurity: 'Notifications and Security',
  termsandConditions: 'Terms and Conditions',
  myProfile: 'My Profile',
  businessNameHere: 'Business Name Here',
  editProfile: 'Edit Profile',
  addressesandTimings: 'Addresses and Timings',
  manageAddresses: 'Manage addresses',
  timings: 'Timings',
  manageBusinessTimings: 'Manage business timings',
  
  changePassword: 'Change password',
  addNewAddress: 'Add new address',
 
  phone: 'Phone',
  businessPhotos: 'Business Photos',
  saveNewPassword: 'Save New Password',
  wallet: 'Wallet',
  currentPassword: 'Current Password',
  newPassword: 'New Password',
  reEnterNewPassword: 'Re-Enter New Password',
  otherPaymentMethods: 'Other Payment Methods',
  addMethod: 'Add payment method',
  notifications: 'Notifications',
  security: 'Security',
  factorAuthentication: '2 Factor Authentication (2FA)',
};
